### ISSUE TITLE
Lens macros?

### ISSUE THREAD

**Issue by sid-kap** [cchalmers/plots#11]
I noticed that there's a lot of code in the library of the form

``` haskell
data Foo b v n = ... 
class HasFoo f a where
  foo :: LensLike' f a (Foo (BackendType a) (V a) (N a))
```

(The actual code in source uses functional dependencies, but to simplify my examples I assume that we used type families in place of functional dependencies. I.e., there is a type family `BackendType :: * -> *`, similar to `V` and `N`.)

This is very similar to:

``` haskell
data Foo b v n = ... 
makeClassy ''Foo
```

which generates

``` haskell
data Foo b v n = ... 
class HasFoo a b v n where
  foo :: Lens' a (Foo b v n)
```

I think I understand why you chose the former over the latter--- you want to generalize over types that might not have a `Lens` into `Foo`, but do have a `Traversal` into `Foo`, or a `Setter` into `Foo`, or something similar. 

While having these classes are definitely useful in some places (although I haven't read enough of the code to fully understand where this extra flexibility is used), they do lead to a lot of boilerplate. (In some files, it seems that 60-80% of the code is simply generating lenses and their associated classes.)

I would like to reduce boilerplate if possible. Here are some ideas I have:
1. Maybe write TemplateHaskell to do this for us (or maybe even try to contribute this into `lens`)? I don't know how widely this pattern is used, so I'm not sure whether the `lens` folks would be interested in merging this.
2. Maybe make the class weaker. For example, if we know we will only ever use `set` and `over` for `Foo`, then make `foo` in the `HasFoo` class have type `Setter a (Foo b v n)` instead of `LensLike' f a (Foo b v n)`.
3. This might be inelegant, but maybe we could make multiple classes: `HasFooLens` and `HasFoo[Traversal/Fold/Setter/whichever one we want to use]`, where `HasFooLens` is the most powerful, `HasFooTraversal` is less powerful but more general, etc. This is less clever than the current solution but _maybe_ could allow us to write less code and be easier to understand for lens novices like me?
4. Maybe find another way to achieve the same thing with less code? I can't think about how else to do this though, and I imagine if there is another way to do this, you would have found it already.

**Comment by cchalmers** [comment]
You're right, I use `LensLike' f` so I can use it as a lens/traversal/setter depending on the context. Here's a few examples of where it can be useful:

``` .haskell
myaxis = r2Axis &~ do
  gridLinesVisible .= True -- all grid lines visible (traversal instance)
  xAxis . gridLinesVisible .= True -- just x-axis (lens instance)

  -- (contrived getter example)
  scatterPlot [(0,0),(1,1)] $ do
    plotStyle &= do -- modify plot style (setter instance)
      c <- use plotColour -- get the plot colour (lens instance)
      when (luminance c < 0.5) $ plotMarker %= scale 2 -- double the marker size for some colours (lens instance)


  connectingLine .= True -- make connecting line true for all plot in the axis 
                         -- (currently traversal instance, may change to setter)
```

Regarding your ideas:
1. Using template haskell to generate these classes would be possible, however I don't think this is a very common pattern (I've never seen it used elsewhere) and, like `makeClassy`, there's no way to add haddock commons to TH generated classes so I wouldn't use it.
2. I guess most people will only use the `Setter` instances for these classes. But I still need some way of retrieving the data when rendering the axis so I'd either need another set of functions or expose the constructors, which I don't really want. Also the `Getter`-like instances can still be useful for more advanced things and debugging.
3. Having separate classes for each case would mean not only lots more classes, but lots more functions names. `gridLinesSetter` `girdLinesTraversal` `gridLinesLens` etc. This kinda defeats of object of using lenses and makes you think about which one you actually are using. Even though the details of how the `LensLike` classes work is quite completed, I hope that actually using them is intuitive (I try to add lots of examples to help with this).
4. Since TH can't generate haddock comments the only way I can think of automating this is to have a custom preprocessor to make them. But I feel this would be more effort than it's worth.

**Comment by sid-kap** [comment]
Hmm. One thing that bothered me about this approach is that it could be difficult for non-lens experts to understand. Do you know of a way to make, for example, the constraints

```
HasPlotOptions Identity a b
HasPlotStyle (Const (PlotStyle b (V a) (N a))) a b
```

easier to understand? One idea I had was maybe something like `(Settable f, HasPlotOptions f a b)` for the first and `(Gettable f, HasPlotOptions f a b)` for the second. The Settable one should work I think, but I couldn't get it to compile. The second one wouldn't work because there is no typeclass called `Gettable`.

**Comment by cchalmers** [comment]
Yeah, they are kinda ugly, but requiring polymorphic arguments like that isn't ideal. Even if you can get it to compile it can lead to errors and complicated types.

My solution with most of these complicated types is to add examples. [`key`](http://cchalmers.github.io/plots/Plots-Types.html#v:key), for example, already has comments to help know where you can use it. Say for `applyLineStyle` I could add comment like

``` .haskell
applyLineStyle :: (InSpace v n t, HasStyle t) => PlotStyle b v n -> t -> t
```

In fact, I might just force that one to be that for simplicity, I don't think I use the other instances.
