### ISSUE TITLE
Status of project

### ISSUE THREAD

**Issue by sooryan** [cchalmers/plots#14]
Hi @cchalmers, with summer of haskell now round the corner, I was looking at the diagrams project list and was interested in the grammar of graphics, which I believe is one of the goals here. 
I wanted to know how far you've gotten with respect to implementing a grammar of graphics. 
I know this is far from an ideal platform to communicate but I couldn't find any other communication information :)

**Comment by cchalmers** [comment]
I'm not sure we faithfully implemented the grammar of graphics but we used lots of ideas from it. I would advise against making a summer of Haskell project on it since it was the focus of last year's GSoC project. Right now I'm focusing on getting an initial release out. There are other things you could work on this for project like 3D plots.

**Comment by ggreif** [comment]
Looks like this can be closed :-)
