### ISSUE TITLE
Drawing heatmap with "NaN" values causes memory leak

### ISSUE THREAD

**Issue by erikryb** [cchalmers/plots#27]
When I try to plot a heatmap with "NaN" values, the program runs out of memory. Example code:

```
import Diagrams.Backend.Rasterific.CmdLine
import Diagrams.Prelude
import Plots

heatMapAxis :: Axis B V2 Double
heatMapAxis = r2Axis &~ do
  display colourBar
  let xs = [[1, read "NaN"]] :: [[Double]]
  heatMap xs $ heatMapSize .= V2 10 10

main :: IO ()
main = r2AxisMain heatMapAxis
```

The prefered behaviour in this case would for instance be that the "NaN" values becomes transparent in the heatmap.

**Comment by cchalmers** [comment]
Making it transparent would be difficult for a few reasons but I could let you pick colours to use to display `NaN` and `Infinity` values.

**Comment by erikryb** [comment]
That would be great!

**Comment by cchalmers** [comment]
I've picked black, white and magenta for the default `-Inf`, `Inf` and `NaN` values. I'm open to suggestions for other colours.

```.haskell
import Diagrams.Backend.Rasterific.CmdLine
import Diagrams.Prelude
import Plots

heatMapAxis :: Axis B V2 Double
heatMapAxis = r2Axis &~ do
  display colourBar
  let xs = [[1,0/0,2], [1/0,3,5], [2,0,-1/0]]
  heatMap xs $ heatMapSize .= V2 10 10

main :: IO ()
main = r2AxisMain heatMapAxis
```

![heatmap_nan](https://cloud.githubusercontent.com/assets/1354887/21163510/629752c4-c18b-11e6-89d9-27ec748cc216.png)

 You can set your own using the `negInfColour`, `infColour` and `nanColour` lenses on the `ColourMap`.

Note that your example still doesn't work without setting the bounds yourself because it gives an empty range for the data `(1,1)`. I'll write something to deal with this case in the next few days when I have time.

**Comment by erikryb** [comment]
Awesome, thanks!
